services:
  - type: web
    name: fraud-detection-app
    env: python
    rootDir: .
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn -w 3 -b 0.0.0.0:$PORT app:app --chdir backend
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.10

